version: "3"
services:
  sonarr:
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
            max-file: "5"
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      TZ: 'America/Denver'
      PGID: 1001
      PUID: 1001
      UMASK_SET: 022
    volumes:
      - /home/joey/docker_apps/sonarr/storage/:/config
      - /media/cifs/freenas.piccola.us/media/:/media
    ports:
      - 8989:8989
    restart: unless-stopped
