---
version: "2"
services:
  unifi-controller:
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
            max-file: "5"
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1001
      - PGID=1001
      - MEM_LIMIT=1024 #optional
    volumes:
      - /home/joey/docker_apps/unifi_controller/config_data/:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
