version: '3'

services:
  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - ./config_data:/etc/letsencrypt
      - ./config_data/cloudflare.ini:/root/cloudflare.ini
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email ${EMAIL}
      --agree-tos --no-eff-email
      --force-renewal
      -d ${D1}

# > cd certbot
# run this docker compose file. it will execute and exit. will update what's in live. env var substitution via .env
# > docker-compose up
# concat the files to make a cert just for haproxy (this is a special format). write the file to /home/joey/docker_apps/haproxy/config_data/cert.pem
# > sudo cat /home/joey/docker_apps/certbot/config_data/live/piccola.us/fullchain.pem /home/joey/docker_apps/certbot/config_data/live/piccola.us/privkey.pem | sudo tee /home/joey/docker_apps/certbot/config_data/live/piccola.us/cert.pem
# restart haproxy
# > cd ../haproxy/; docker-compose restart
