---
version: "3.9"

networks:
  haproxy:
    name: haproxy
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.208.0/20
          gateway: 192.168.208.1

services:
  haproxy:
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
            max-file: "5"
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    networks:
      - haproxy
    volumes:
      - ./config_data/:/usr/local/etc/haproxy:ro
    ports:
      - 8404:8404
      - 443:443
    restart: unless-stopped
