version: '2'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - 8200:8200
    restart: always
    environment:
        - VAULT_LOCAL_CONFIG={"backend":{"file":{"path":"/vault/file"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}},"ui":true}
    volumes:
      - /home/joey/docker_apps/vault/config_data/logs/:/vault/logs
      - /home/joey/docker_apps/vault/config_data/file/:/vault/file
    cap_add:
      - IPC_LOCK
    command:
      - "server"