version: "3"

services:

  telegraf:
    container_name: telegraf_vsphere
    image: telegraf:latest
    volumes:
      - /home/joey/docker_apps/telegraf_vsphere/config_data/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always
