version: "3"

services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
       - '/var/run/docker.sock:/var/run/docker.sock'
       - '/home/joey/docker_storage/portainer/portainer_data:/data'
    ports:
      - '9000:9000'
    restart: always