version: '3'
services:
  homeassistant:
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
            max-file: "5"
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/joey/docker_apps/home_assistant/config_data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host