version: '3'

services:
  esphome:
    image: esphome/esphome
    volumes:
      - /home/joey/docker_apps/esphome/config_data:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always