---
version: "3"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    networks:
      default:
        ipv4_address: 10.0.3.241
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - SERVERURL=vpn-wg.piccola.us #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=10.0.3.24 #optional
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=10.0.3.0/24,10.13.13.0/24 #optional
    volumes:
      - /home/joey/docker_apps/wireguard/config_data/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

networks:
  default:
    external:
      name: mynet